-file("/home/parallels/.asdf/installs/erlang/26.1.2/lib/parsetools-2.5/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(imersia_maths_leex).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/grammars/imersia_maths_leex.xrl", 47).

extract_function_name(TokenChars) -> re:replace(TokenChars, "\\s+|\\(", "", [global,{return,list}]).

-file("/home/parallels/.asdf/installs/erlang/26.1.2/lib/parsetools-2.5/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

%% string(InChars) ->
%% string(InChars, Loc) ->
%% {ok,Tokens,EndLoc} | {error,ErrorInfo,EndLoc}.
%% Loc is the starting location of the token, while EndLoc is the first not scanned
%% location. Location is either Line or {Line,Column}, depending on the "error_location" option.

string(Ics) -> 
    string(Ics,1).
string(Ics,L0) -> 
    string(Ics, L0, 1, Ics, []).
string(Ics, L0, C0, Tcs, Ts) -> 
    case do_string(Ics, L0, C0, Tcs, Ts) of
        {ok, T, {L,_}} -> {ok, T, L};
        {error, {{EL,_},M,D}, {L,_}} ->
            EI = {EL,M,D},
            {error, EI, L}
    end.

do_string([], L, C, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),{L,C}};
do_string(Ics0, L0, C0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, C0, 0, reject, 0) of
        {A,Alen,Ics1,L1,_C1} ->                  % Accepting end state
            C2 = adjust_col(Tcs, Alen, C0),
            string_cont(Ics1, L1, C2, yyaction(A, Alen, Tcs, L0, C0), Ts);
        {A,Alen,Ics1,L1,_C1,_S1} ->              % Accepting transition state
            C2 = adjust_col(Tcs, Alen, C0),
            string_cont(Ics1, L1, C2, yyaction(A, Alen, Tcs, L0, C0), Ts);
        {reject,_Alen,Tlen,_Ics1,_L1,_C1,_S1} ->  % After a non-accepting state
            {error,{{L0, C0} ,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},{L0, C0}};
        {A,Alen,Tlen,_Ics1,L1, C1,_S1}->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            C2 = adjust_col(Tcs, Alen, C1),
            string_cont(Tcs1, L2, C2, yyaction(A, Alen, Tcs, L0,C0), Ts)
    end.

%% string_cont(RestChars, Line, Col, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/5}).

string_cont(Rest, Line, Col, {token,T}, Ts) ->
    do_string(Rest, Line, Col, Rest, [T|Ts]);
string_cont(Rest, Line, Col, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, [T|Ts]);
string_cont(Rest, Line, Col, {end_token,T}, Ts) ->
    do_string(Rest, Line, Col, Rest, [T|Ts]);
string_cont(Rest, Line, Col, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, [T|Ts]);
string_cont(Rest, Line, Col, skip_token, Ts) ->
    do_string(Rest, Line, Col, Rest, Ts);
string_cont(Rest, Line, Col, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, Ts);
string_cont(_Rest, Line, Col, {error,S}, _Ts) ->
    {error,{{Line, Col},?MODULE,{user,S}},{Line,Col}}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Loc) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCol,AccAction,AccLen}

token(Cont,Chars) -> 
    token(Cont,Chars,1).
token(Cont, Chars, Line) -> 
    case do_token(Cont,Chars,Line,1) of
        {more, _} = C -> C;
        {done, Ret0, R} ->
            Ret1 = case Ret0 of
                {ok, T, {L,_}} -> {ok, T, L};
                {eof, {L,_}} -> {eof, L};
                {error, {{EL,_},M,D},{L,_}} -> {error, {EL,M,D},L}
            end,
            {done, Ret1, R}
    end.

do_token([], Chars, Line, Col) ->
    token(yystate(), Chars, Line, Col, Chars, 0, Line, Col, reject, 0);
do_token({token,State,Line,Col,Tcs,Tlen,Tline,Tcol,Action,Alen}, Chars, _, _) ->
    token(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Action, Alen).

%% token(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1,C1} ->
            C2 = adjust_col(Tcs, Alen1, C1),
            token_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,C1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,C1,Tcs,Alen1,Tline,Tcol,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->               % Take what we got
            C2 = adjust_col(Tcs, Alen1, C1),
            token_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,C1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{{Tline,Tcol},?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},{L1,C1}};
                     true -> {eof,{L1,C1}}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,_L1,_C1,_S1} ->    % No token match
            Error = {{Tline,Tcol},?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,{Tline,Tcol}},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_C1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            C2 = C0 + Alen1,
            token_cont(Tcs1, L2, C2, yyaction(A1, Alen1, Tcs, Tline, Tcol))
    end.

%% token_cont(RestChars, Line, Col, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/4}).

token_cont(Rest, Line, Col, {token,T}) ->
    {done,{ok,T,{Line,Col}},Rest};
token_cont(Rest, Line, Col, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,{Line,Col}},NewRest};
token_cont(Rest, Line, Col, {end_token,T}) ->
    {done,{ok,T,{Line,Col}},Rest};
token_cont(Rest, Line, Col, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,{Line,Col}},NewRest};
token_cont(Rest, Line, Col, skip_token) ->
    token(yystate(), Rest, Line, Col, Rest, 0, Line, Col, reject, 0);
token_cont(Rest, Line, Col, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, reject, 0);
token_cont(Rest, Line, Col, {error,S}) ->
    {done,{error,{{Line, Col},?MODULE,{user,S}},{Line, Col}},Rest}.

%% tokens(Continuation, Chars) ->
%% tokens(Continuation, Chars, Loc) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCur,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCur,Error,AccAction,AccLen}

tokens(Cont,Chars) -> 
    tokens(Cont,Chars,1).
tokens(Cont, Chars, Line) -> 
    case do_tokens(Cont,Chars,Line,1) of
        {more, _} = C -> C;
        {done, Ret0, R} ->
            Ret1 = case Ret0 of
                {ok, T, {L,_}} -> {ok, T, L};
                {eof, {L,_}} -> {eof, L};
                {error, {{EL,_},M,D},{L,_}} -> {error, {EL,M,D},L}
            end,
            {done, Ret1, R}
    end.

do_tokens([], Chars, Line, Col) ->
    tokens(yystate(), Chars, Line, Col, Chars, 0, Line, Col, [], reject, 0);
do_tokens({tokens,State,Line,Col,Tcs,Tlen,Tline,Tcol,Ts,Action,Alen}, Chars, _,_) ->
    tokens(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Ts, Action, Alen);
do_tokens({skip_tokens,State,Line, Col, Tcs,Tlen,Tline,Tcol,Error,Action,Alen}, Chars, _,_) ->
    skip_tokens(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Error, Action, Alen).

%% tokens(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol,Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1,C1} ->
            C2 = adjust_col(Tcs, Alen1, C1),
            tokens_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline, Tcol), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,C1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,C1,Tcs,Alen1,Tline,Tcol,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->               % Take what we got
            C2 = adjust_col(Tcs, Alen1, C1),
            tokens_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,C1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{{Tline,Tcol},?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},{L1,C1}};
                     Ts == [] -> {eof,{L1,C1}};
                     true -> {ok,yyrev(Ts),{L1,C1}}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            %% Skip rest of tokens.
            Error = {{L1,C1},?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, C1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_C1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline,Tcol),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            C2 = C0 + Alen1,
            tokens_cont(Tcs1, L2, C2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Column, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/5}).

tokens_cont(Rest, Line, Col, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, [T|Ts], reject, 0);
tokens_cont(Rest, Line, Col, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, [T|Ts], reject, 0);
tokens_cont(Rest, Line, Col, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),{Line,Col}},Rest};
tokens_cont(Rest, Line, Col, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),{Line, Col}},NewRest};
tokens_cont(Rest, Line, Col, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Ts, reject, 0);
tokens_cont(Rest, Line, Col, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Ts, reject, 0);
tokens_cont(Rest, Line, Col, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, Col, {{Line,Col},?MODULE,{user,S}}).

%% skip_tokens(InChars, Line, Col, Error) -> {done,{error,Error,{Line,Col}},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Col, Error) ->
    skip_tokens(yystate(), Ics, Line, Col, Ics, 0, Line, Col, Error, reject, 0).

%% skip_tokens(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1, C1} ->                  % Accepting end state
            skip_cont(Ics1, L1, C1, yyaction(A1, Alen1, Tcs, Tline, Tcol), Error);
        {A1,Alen1,[],L1,C1, S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,C1,Tcs,Alen1,Tline,Tcol,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->
            skip_cont(Ics1, L1, C1, yyaction(A1, Alen1, Tcs, Tline, Tcol), Error);
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,C1,_S1} ->
            {done,{error,Error,{L1,C1}},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, C1,Error);
        {A1,Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline, Tcol),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, C1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Col, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/5}).

skip_cont(Rest, Line, Col, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {end_token,_T}, Error) ->
    {done,{error,Error,{Line,Col}},Rest};
skip_cont(Rest, Line, Col, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,{Line,Col}},NewRest};
skip_cont(Rest, Line, Col, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% adjust_col(Chars, AcceptLength, Col) -> NewCol
%% Handle newlines, tabs and unicode chars.
adjust_col(_, 0, Col) ->
    Col;
adjust_col([$\n | R], L, _) ->
    adjust_col(R, L-1, 1);
adjust_col([$\t | R], L, Col) ->
    adjust_col(R, L-1, tab_forward(Col)+1);
adjust_col([C | R], L, Col) when C>=0 andalso C=< 16#7F ->
    adjust_col(R, L-1, Col+1);
adjust_col([C | R], L, Col) when C>= 16#80 andalso C=< 16#7FF ->
    adjust_col(R, L-1, Col+2);
adjust_col([C | R], L, Col) when C>= 16#800 andalso C=< 16#FFFF ->
    adjust_col(R, L-1, Col+3);
adjust_col([C | R], L, Col) when C>= 16#10000 andalso C=< 16#10FFFF ->
    adjust_col(R, L-1, Col+4).

tab_forward(C) ->
    D = C rem tab_size(),
    A = tab_size()-D,
    C+A.

tab_size() -> 8.

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, Col, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line, Col} |
%% {Action, AcceptLen, RestChars, Line, Col, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, Col, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, Col, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/imersia_maths_leex.erl", 341).
yystate() -> 96.

yystate(99, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(97, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(99, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(97, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(99, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(97, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(99, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,99};
yystate(98, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(98, Ics, Line, Col, Tlen+1, 28, Tlen);
yystate(98, Ics, Line, Col, Tlen, _, _) ->
    {28,Tlen,Ics,Line,Col,98};
yystate(97, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(97, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(93, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(97, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(93, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(97, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,97};
yystate(96, [125|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [124|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(88, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [116|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [102|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [101|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(85, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [62|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [61|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [60|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [47|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [44|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [43|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [42|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [41|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [40|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [39|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [38|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(78, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [37|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(86, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [33|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(90, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [32|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(98, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(45, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(73, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 71, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(73, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 103, C =< 115 ->
    yystate(60, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 117, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,96};
yystate(95, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(99, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(95, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(99, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(95, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(99, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(95, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,95};
yystate(94, Ics, Line, Col, Tlen, _, _) ->
    {22,Tlen,Ics,Line,Col};
yystate(93, Ics, Line, Col, Tlen, _, _) ->
    {1,Tlen,Ics,Line,Col};
yystate(92, Ics, Line, Col, Tlen, _, _) ->
    {29,Tlen,Ics,Line,Col};
yystate(91, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(95, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(91, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(95, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(91, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(95, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(91, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,91};
yystate(90, [61|Ics], Line, Col, Tlen, _, _) ->
    yystate(94, Ics, Line, Col, Tlen+1, 25, Tlen);
yystate(90, Ics, Line, Col, Tlen, _, _) ->
    {25,Tlen,Ics,Line,Col,90};
yystate(89, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(89, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(89, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(89, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(89, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(89, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(89, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(89, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(89, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(24, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(89, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(24, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(89, [C|Ics], Line, Col, Tlen, _, _) when C >= 71, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(89, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(24, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(89, [C|Ics], Line, Col, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(89, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,89};
yystate(88, [124|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(88, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,88};
yystate(87, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(91, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(87, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(91, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(87, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(91, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(87, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,87};
yystate(86, Ics, Line, Col, Tlen, _, _) ->
    {15,Tlen,Ics,Line,Col};
yystate(85, [114|Ics], Line, Col, Tlen, _, _) ->
    yystate(81, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(85, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(85, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(85, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(85, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(85, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(85, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(85, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(85, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(85, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(89, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(85, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(89, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(85, [C|Ics], Line, Col, Tlen, _, _) when C >= 71, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(85, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(89, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(85, [C|Ics], Line, Col, Tlen, _, _) when C >= 103, C =< 113 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(85, [C|Ics], Line, Col, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(85, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,85};
yystate(84, Ics, Line, Col, Tlen, _, _) ->
    {24,Tlen,Ics,Line,Col};
yystate(83, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(87, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(83, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(87, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(83, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(87, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(83, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,83};
yystate(82, Ics, Line, Col, Tlen, _, _) ->
    {23,Tlen,Ics,Line,Col};
yystate(81, [114|Ics], Line, Col, Tlen, _, _) ->
    yystate(77, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(81, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(81, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(81, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(81, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(81, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(81, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(81, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(81, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(81, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(81, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(81, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(81, [C|Ics], Line, Col, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(81, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,81};
yystate(80, [114|Ics], Line, Col, Tlen, _, _) ->
    yystate(76, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(80, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(80, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(80, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(80, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(80, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(80, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(80, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(80, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(80, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(80, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(80, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(80, [C|Ics], Line, Col, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(80, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,80};
yystate(79, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(83, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(79, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(83, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(79, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(83, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(79, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,79};
yystate(78, [38|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(82, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(78, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,78};
yystate(77, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(77, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(77, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(77, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(77, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(77, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(77, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(77, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(77, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(60, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(77, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(77, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 4, Tlen);
yystate(77, Ics, Line, Col, Tlen, _, _) ->
    {4,Tlen,Ics,Line,Col,77};
yystate(76, [117|Ics], Line, Col, Tlen, _, _) ->
    yystate(72, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(76, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(76, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(76, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(76, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(76, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(76, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(76, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(76, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(76, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(76, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(76, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(76, [C|Ics], Line, Col, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(76, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,76};
yystate(75, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(79, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(75, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(79, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(75, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(79, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(75, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,75};
yystate(74, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col};
yystate(73, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(73, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(73, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(73, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(73, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(73, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(73, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(73, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(73, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(89, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(73, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(89, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(73, [C|Ics], Line, Col, Tlen, _, _) when C >= 71, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(73, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(89, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(73, [C|Ics], Line, Col, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(73, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,73};
yystate(72, [101|Ics], Line, Col, Tlen, _, _) ->
    yystate(68, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(72, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(72, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(72, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(72, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(72, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(72, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(72, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(72, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(72, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(72, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(72, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(72, [C|Ics], Line, Col, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(72, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,72};
yystate(71, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(75, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(71, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(75, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(71, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(75, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(71, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,71};
yystate(70, [39|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(70, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(70, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(70, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(70, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 35, C =< 38 ->
    yystate(70, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 40 ->
    yystate(70, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(70, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,70};
yystate(69, [61|Ics], Line, Col, Tlen, _, _) ->
    yystate(65, Ics, Line, Col, Tlen+1, 17, Tlen);
yystate(69, Ics, Line, Col, Tlen, _, _) ->
    {17,Tlen,Ics,Line,Col,69};
yystate(68, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(68, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(68, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(68, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(68, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(68, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(68, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(68, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(68, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(60, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(68, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(68, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 2, Tlen);
yystate(68, Ics, Line, Col, Tlen, _, _) ->
    {2,Tlen,Ics,Line,Col,68};
yystate(67, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(71, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(67, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(71, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(67, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(71, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(67, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,67};
yystate(66, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(70, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(66, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(70, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(66, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(70, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(66, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 35, C =< 38 ->
    yystate(70, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(66, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 40 ->
    yystate(70, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(66, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,66};
yystate(65, Ics, Line, Col, Tlen, _, _) ->
    {18,Tlen,Ics,Line,Col};
yystate(64, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(64, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(64, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(64, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(64, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 58 ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(64, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 91 ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(64, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(64, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,64};
yystate(63, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(63, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(63, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(63, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,63};
yystate(62, Ics, Line, Col, Tlen, _, _) ->
    {9,Tlen,Ics,Line,Col};
yystate(61, [61|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(61, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,61};
yystate(60, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(60, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(60, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(60, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(60, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(60, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(60, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(60, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(60, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(60, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(60, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(60, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,60};
yystate(59, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(63, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(59, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(63, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(59, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(63, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(59, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,59};
yystate(58, Ics, Line, Col, Tlen, _, _) ->
    {10,Tlen,Ics,Line,Col};
yystate(57, Ics, Line, Col, Tlen, _, _) ->
    {21,Tlen,Ics,Line,Col};
yystate(56, Ics, Line, Col, Tlen, _, _) ->
    {5,Tlen,Ics,Line,Col};
yystate(55, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(55, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,55};
yystate(54, Ics, Line, Col, Tlen, _, _) ->
    {13,Tlen,Ics,Line,Col};
yystate(53, [61|Ics], Line, Col, Tlen, _, _) ->
    yystate(49, Ics, Line, Col, Tlen+1, 19, Tlen);
yystate(53, Ics, Line, Col, Tlen, _, _) ->
    {19,Tlen,Ics,Line,Col,53};
yystate(52, Ics, Line, Col, Tlen, _, _) ->
    {6,Tlen,Ics,Line,Col};
yystate(51, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(51, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(55, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(51, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(55, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(51, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,51};
yystate(50, Ics, Line, Col, Tlen, _, _) ->
    {11,Tlen,Ics,Line,Col};
yystate(49, Ics, Line, Col, Tlen, _, _) ->
    {20,Tlen,Ics,Line,Col};
yystate(48, [40|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [32|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,48};
yystate(47, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(51, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(47, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(51, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(47, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(51, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(47, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,47};
yystate(46, Ics, Line, Col, Tlen, _, _) ->
    {16,Tlen,Ics,Line,Col};
yystate(45, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(18, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(45, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(13, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(45, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(41, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(45, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(41, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(45, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,45};
yystate(44, [97|Ics], Line, Col, Tlen, _, _) ->
    yystate(40, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(44, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(44, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(44, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(44, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(44, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(44, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(44, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(44, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(44, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(89, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(44, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(89, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(44, [C|Ics], Line, Col, Tlen, _, _) when C >= 71, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(44, [C|Ics], Line, Col, Tlen, _, _) when C >= 98, C =< 102 ->
    yystate(89, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(44, [C|Ics], Line, Col, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(44, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,44};
yystate(43, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(47, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(47, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(47, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(43, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,43};
yystate(42, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(14, Ics, Line, Col, Tlen+1, 12, Tlen);
yystate(42, Ics, Line, Col, Tlen, _, _) ->
    {12,Tlen,Ics,Line,Col,42};
yystate(41, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(37, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(37, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(37, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(41, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,41};
yystate(40, [108|Ics], Line, Col, Tlen, _, _) ->
    yystate(36, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(40, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(40, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(40, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(40, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(40, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(40, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(40, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(40, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(40, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(24, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(40, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(24, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(40, [C|Ics], Line, Col, Tlen, _, _) when C >= 71, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(40, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(24, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(40, [C|Ics], Line, Col, Tlen, _, _) when C >= 103, C =< 107 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(40, [C|Ics], Line, Col, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(40, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,40};
yystate(39, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(43, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(43, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(43, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(39, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,39};
yystate(38, Ics, Line, Col, Tlen, _, _) ->
    {14,Tlen,Ics,Line,Col};
yystate(37, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(33, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(37, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(33, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(37, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(33, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(37, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,37};
yystate(36, [115|Ics], Line, Col, Tlen, _, _) ->
    yystate(32, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(36, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(36, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(36, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(36, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(36, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(36, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(36, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(36, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(36, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(36, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(36, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(36, [C|Ics], Line, Col, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(36, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,36};
yystate(35, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(35, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,35};
yystate(34, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(34, [43|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(26, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(34, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,34};
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(29, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(29, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(33, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(29, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(33, Ics, Line, Col, Tlen, _, _) ->
    {0,Tlen,Ics,Line,Col,33};
yystate(32, [101|Ics], Line, Col, Tlen, _, _) ->
    yystate(28, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(32, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(32, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(32, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(32, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(32, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(32, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(32, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(32, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Col, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(32, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,32};
yystate(31, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(35, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(35, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(31, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,31};
yystate(30, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(26, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(30, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,30};
yystate(29, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(25, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(25, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,29};
yystate(28, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(28, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(28, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(28, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(28, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(28, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(28, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(28, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(60, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(28, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 3, Tlen);
yystate(28, Ics, Line, Col, Tlen, _, _) ->
    {3,Tlen,Ics,Line,Col,28};
yystate(27, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(31, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(31, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(31, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(27, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,27};
yystate(26, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(26, Ics, Line, Col, Tlen+1, 27, Tlen);
yystate(26, Ics, Line, Col, Tlen, _, _) ->
    {27,Tlen,Ics,Line,Col,26};
yystate(25, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(21, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(25, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(21, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(25, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(21, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(25, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,25};
yystate(24, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(24, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(24, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(24, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(24, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(24, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(24, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(24, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(24, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(20, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(24, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(20, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(24, [C|Ics], Line, Col, Tlen, _, _) when C >= 71, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(24, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(20, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(24, [C|Ics], Line, Col, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(24, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,24};
yystate(23, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(23, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(27, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(23, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(27, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(23, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,23};
yystate(22, [101|Ics], Line, Col, Tlen, _, _) ->
    yystate(34, Ics, Line, Col, Tlen+1, 27, Tlen);
yystate(22, [69|Ics], Line, Col, Tlen, _, _) ->
    yystate(34, Ics, Line, Col, Tlen+1, 27, Tlen);
yystate(22, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(22, Ics, Line, Col, Tlen+1, 27, Tlen);
yystate(22, Ics, Line, Col, Tlen, _, _) ->
    {27,Tlen,Ics,Line,Col,22};
yystate(21, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(17, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(17, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(17, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(21, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,21};
yystate(20, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(20, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(20, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(20, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(20, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(20, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(20, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(20, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(20, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(20, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(16, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(20, [C|Ics], Line, Col, Tlen, _, _) when C >= 71, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(20, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(16, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(20, [C|Ics], Line, Col, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(20, Ics, Line, Col, Tlen, _, _) ->
    {0,Tlen,Ics,Line,Col,20};
yystate(19, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(23, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(19, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(23, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(19, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(23, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(19, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,19};
yystate(18, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(22, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(18, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,18};
yystate(17, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(17, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,17};
yystate(16, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(16, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(16, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(16, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(16, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(16, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(16, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(16, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(16, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(12, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(16, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(12, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(16, [C|Ics], Line, Col, Tlen, _, _) when C >= 71, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(16, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(12, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(16, [C|Ics], Line, Col, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(16, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,16};
yystate(15, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(15, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,15};
yystate(14, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(18, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(14, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(14, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,14};
yystate(13, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(18, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(13, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(9, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(13, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(37, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(13, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(37, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(13, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,13};
yystate(12, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(12, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(12, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(12, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(12, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(12, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(12, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(12, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(12, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(12, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(8, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(12, [C|Ics], Line, Col, Tlen, _, _) when C >= 71, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(12, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(8, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(12, [C|Ics], Line, Col, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(12, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,12};
yystate(11, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(15, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(15, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(11, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,11};
yystate(10, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(18, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(10, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(14, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(10, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,10};
yystate(9, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(18, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(9, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(9, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(33, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(9, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(33, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(9, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,9};
yystate(8, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(8, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(8, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(8, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(8, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(8, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(8, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(8, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(8, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(4, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(8, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(4, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(8, [C|Ics], Line, Col, Tlen, _, _) when C >= 71, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(8, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(4, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(8, [C|Ics], Line, Col, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(8, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,8};
yystate(7, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(11, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(11, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(11, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(7, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,7};
yystate(6, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(18, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(6, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(10, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(6, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(17, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(6, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(17, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(6, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,6};
yystate(5, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(18, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(1, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(29, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(5, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(29, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(5, Ics, Line, Col, Tlen, _, _) ->
    {0,Tlen,Ics,Line,Col,5};
yystate(4, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(4, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(4, [91|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(4, [58|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(4, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(4, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(4, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(4, [33|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(4, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(4, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(4, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(4, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(60, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(4, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,4};
yystate(3, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(7, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(3, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(7, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(3, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(7, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(3, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,3};
yystate(2, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(18, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(2, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(6, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(2, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(21, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(2, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(21, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(2, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,2};
yystate(1, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(18, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(1, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(2, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(1, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(25, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(1, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(25, Ics, Line, Col, Tlen+1, 26, Tlen);
yystate(1, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col,1};
yystate(0, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(3, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(3, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(3, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(0, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,0};
yystate(S, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine, TokenCol) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, _, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars);
yyaction(1, TokenLen, YYtcs, _, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars);
yyaction(2, _, _, _, _) ->
    yyaction_2();
yyaction(3, _, _, _, _) ->
    yyaction_3();
yyaction(4, _, _, _, _) ->
    yyaction_4();
yyaction(5, TokenLen, YYtcs, _, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars);
yyaction(6, TokenLen, YYtcs, _, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars);
yyaction(7, TokenLen, YYtcs, _, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars);
yyaction(8, TokenLen, YYtcs, _, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars);
yyaction(9, _, _, _, _) ->
    yyaction_9();
yyaction(10, _, _, _, _) ->
    yyaction_10();
yyaction(11, _, _, _, _) ->
    yyaction_11();
yyaction(12, _, _, _, _) ->
    yyaction_12();
yyaction(13, _, _, _, _) ->
    yyaction_13();
yyaction(14, _, _, _, _) ->
    yyaction_14();
yyaction(15, _, _, _, _) ->
    yyaction_15();
yyaction(16, _, _, _, _) ->
    yyaction_16();
yyaction(17, _, _, _, _) ->
    yyaction_17();
yyaction(18, _, _, _, _) ->
    yyaction_18();
yyaction(19, _, _, _, _) ->
    yyaction_19();
yyaction(20, _, _, _, _) ->
    yyaction_20();
yyaction(21, _, _, _, _) ->
    yyaction_21();
yyaction(22, _, _, _, _) ->
    yyaction_22();
yyaction(23, _, _, _, _) ->
    yyaction_23();
yyaction(24, _, _, _, _) ->
    yyaction_24();
yyaction(25, _, _, _, _) ->
    yyaction_25();
yyaction(26, TokenLen, YYtcs, _, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_26(TokenChars);
yyaction(27, TokenLen, YYtcs, _, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_27(TokenChars);
yyaction(28, _, _, _, _) ->
    yyaction_28();
yyaction(29, _, _, _, _) ->
    yyaction_29();
yyaction(_, _, _, _, _) -> error.

-compile({inline,yyaction_0/1}).
-file("src/grammars/imersia_maths_leex.xrl", 13).
yyaction_0(TokenChars) ->
     { token, { str, 1, list_to_binary (TokenChars) } } .

-compile({inline,yyaction_1/1}).
-file("src/grammars/imersia_maths_leex.xrl", 15).
yyaction_1(TokenChars) ->
     { token, { str, 1, list_to_binary (TokenChars) } } .

-compile({inline,yyaction_2/0}).
-file("src/grammars/imersia_maths_leex.xrl", 16).
yyaction_2() ->
     { token, { bool, 1, true } } .

-compile({inline,yyaction_3/0}).
-file("src/grammars/imersia_maths_leex.xrl", 17).
yyaction_3() ->
     { token, { bool, 1, false } } .

-compile({inline,yyaction_4/0}).
-file("src/grammars/imersia_maths_leex.xrl", 18).
yyaction_4() ->
     { token, { err, 1, err } } .

-compile({inline,yyaction_5/1}).
-file("src/grammars/imersia_maths_leex.xrl", 19).
yyaction_5(TokenChars) ->
     { token, { func, 1, list_to_binary (extract_function_name (TokenChars)) }, "(" } .

-compile({inline,yyaction_6/1}).
-file("src/grammars/imersia_maths_leex.xrl", 20).
yyaction_6(TokenChars) ->
     { token, { var, 1, list_to_binary (TokenChars) } } .

-compile({inline,yyaction_7/1}).
-file("src/grammars/imersia_maths_leex.xrl", 21).
yyaction_7(TokenChars) ->
     { token, { var, 1, list_to_binary (TokenChars) } } .

-compile({inline,yyaction_8/1}).
-file("src/grammars/imersia_maths_leex.xrl", 22).
yyaction_8(TokenChars) ->
     { token, { str, 1, list_to_binary (string : trim (TokenChars, both, "'")) } } .

-compile({inline,yyaction_9/0}).
-file("src/grammars/imersia_maths_leex.xrl", 23).
yyaction_9() ->
     { token, { lbr, 1 } } .

-compile({inline,yyaction_10/0}).
-file("src/grammars/imersia_maths_leex.xrl", 24).
yyaction_10() ->
     { token, { rbr, 1 } } .

-compile({inline,yyaction_11/0}).
-file("src/grammars/imersia_maths_leex.xrl", 25).
yyaction_11() ->
     { token, { '+', 1 } } .

-compile({inline,yyaction_12/0}).
-file("src/grammars/imersia_maths_leex.xrl", 26).
yyaction_12() ->
     { token, { '-', 1 } } .

-compile({inline,yyaction_13/0}).
-file("src/grammars/imersia_maths_leex.xrl", 27).
yyaction_13() ->
     { token, { '*', 1 } } .

-compile({inline,yyaction_14/0}).
-file("src/grammars/imersia_maths_leex.xrl", 28).
yyaction_14() ->
     { token, { '/', 1 } } .

-compile({inline,yyaction_15/0}).
-file("src/grammars/imersia_maths_leex.xrl", 29).
yyaction_15() ->
     { token, { '%', 1 } } .

-compile({inline,yyaction_16/0}).
-file("src/grammars/imersia_maths_leex.xrl", 30).
yyaction_16() ->
     { token, { ',', 1 } } .

-compile({inline,yyaction_17/0}).
-file("src/grammars/imersia_maths_leex.xrl", 31).
yyaction_17() ->
     { token, { gt, 1 } } .

-compile({inline,yyaction_18/0}).
-file("src/grammars/imersia_maths_leex.xrl", 32).
yyaction_18() ->
     { token, { gte, 1 } } .

-compile({inline,yyaction_19/0}).
-file("src/grammars/imersia_maths_leex.xrl", 33).
yyaction_19() ->
     { token, { lt, 1 } } .

-compile({inline,yyaction_20/0}).
-file("src/grammars/imersia_maths_leex.xrl", 34).
yyaction_20() ->
     { token, { lte, 1 } } .

-compile({inline,yyaction_21/0}).
-file("src/grammars/imersia_maths_leex.xrl", 35).
yyaction_21() ->
     { token, { eq, 1 } } .

-compile({inline,yyaction_22/0}).
-file("src/grammars/imersia_maths_leex.xrl", 36).
yyaction_22() ->
     { token, { neq, 1 } } .

-compile({inline,yyaction_23/0}).
-file("src/grammars/imersia_maths_leex.xrl", 37).
yyaction_23() ->
     { token, { 'and', 1 } } .

-compile({inline,yyaction_24/0}).
-file("src/grammars/imersia_maths_leex.xrl", 38).
yyaction_24() ->
     { token, { 'or', 1 } } .

-compile({inline,yyaction_25/0}).
-file("src/grammars/imersia_maths_leex.xrl", 39).
yyaction_25() ->
     { token, { 'not', 1 } } .

-compile({inline,yyaction_26/1}).
-file("src/grammars/imersia_maths_leex.xrl", 40).
yyaction_26(TokenChars) ->
     { token, { num, 1, list_to_integer (TokenChars) } } .

-compile({inline,yyaction_27/1}).
-file("src/grammars/imersia_maths_leex.xrl", 41).
yyaction_27(TokenChars) ->
     { token, { num, 1, list_to_float (TokenChars) } } .

-compile({inline,yyaction_28/0}).
-file("src/grammars/imersia_maths_leex.xrl", 42).
yyaction_28() ->
     skip_token .

-compile({inline,yyaction_29/0}).
-file("src/grammars/imersia_maths_leex.xrl", 43).
yyaction_29() ->
     { token, { '$end' } } .
-file("/home/parallels/.asdf/installs/erlang/26.1.2/lib/parsetools-2.5/include/leexinc.hrl", 344).
